import './js/books-api.js';
import './js/feedbacks.js';
import './js/hero.js';
import './js/events.js';
import './js/header.js';
import './js/footer.js';
import './js/modal.js';
import './js/book-modal.js';
import './js/scroll-up.js';
